apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/results-svc/k8s?ref=51a6bb7d488b7e912e2fc8b10753a53325f64e56

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: results-config

images:
- name: results-svc
  newName: ghcr.io/flawmop/results-svc
  newTag: 51a6bb7d488b7e912e2fc8b10753a53325f64e56

replicas:
- count: 1
  name: results-svc
