apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/results-svc/k8s?ref=1f5765c8da102aef22bf012ab452f57914d15fa6

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: results-config

images:
- name: results-svc
  newName: ghcr.io/flawmop/results-svc
  newTag: 1f5765c8da102aef22bf012ab452f57914d15fa6

replicas:
- count: 1
  name: results-svc
